### PR TITLE
Small changes to make examples more consistent and Perl6ish

### PR DESCRIPTION
**Pull request by zaucker**
BTW, [issue 10](https://github.com/Tux/CSV/issues/10)

Unfortunately, beyond my capabilities to track down/fix.

### CODE REVIEW

**Comment by Tux** [comment]
Thanks for your contribution. Next time please follow the style as described in CONTRIBUTING.md

**Comment by zaucker** [comment]
Where would I find CONTRIBUTING.md?

**Comment by Tux** [comment]
Good point :) I forgot to copy it from Text::CSV_XS. I will add it now, of course with changes needed for perl5 → perl6. Sorry!

**Comment by zaucker** [comment]
:-)

Fritz Zaucker
Platanen 42
4600 Olten
+41 62 212 7712

**Comment by zaucker** [comment]
Just read the new CONTRIBUTING.md. Do I understand correctly, you don't want PRs, but only issues?

And about issue 10 mentioned in the initial comment: I was not really sure where to submit that to. Was it correct here? Or is it actually a bug in perl6? I submitted it here because `perl6 --doc` on some of my own files worked just fine and I thus thought it is a problem with CVS.pod6. But I might be mistaken.

**Comment by Tux** [comment]
No, PR's are fine, as long as they "match" the guidelines in CONTRIBUTING.md . Sorry, but I am a style/layout fetishist :)
I've put the issue#10 Q on IRC

**Pull request merged**
